In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px

In [2]:
path = r"C:\Users\USER\Desktop\Jupyter_Lab\UANL\SEM7\Mineria\MineriaUANL\P1\spotify-2023.xlsx"
data = pd.read_excel(path)
data = data.sort_values("released_year",ascending=False)

In [3]:
data

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
210,Abcdario,"Junior H, Eden Muï¿½ï",2,2023,5,13,262,5,89933133,8,...,129,G#,Major,70,42,43,78,0,11,3
351,PERO Tï¿,"Karol G, Quevedo",2,2023,2,23,387,11,93438910,11,...,140,F#,Major,86,68,79,39,0,11,29
174,ýýýýýýýýýýýý,YOASOBI,1,2023,4,12,356,16,143573775,35,...,166,C#,Major,57,84,94,11,0,37,9
348,Red Ruby Da Sleeze,Nicki Minaj,1,2023,3,3,1168,0,81419389,45,...,98,C#,Major,70,29,73,12,0,11,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
459,A Holly Jolly Christmas - Single Version,Burl Ives,1,1952,1,1,7930,0,395591396,108,...,140,NaN,Major,67,81,36,64,0,15,3
466,Let It Snow! Let It Snow! Let It Snow!,"Frank Sinatra, B. Swanson Quartet",2,1950,1,1,10585,0,473248298,126,...,143,D,Major,60,86,32,88,0,34,6
460,The Christmas Song (Merry Christmas To You) - ...,Nat King Cole,1,1946,11,1,11500,0,389771964,140,...,139,C#,Major,36,22,15,84,0,11,4
469,White Christmas,"Bing Crosby, John Scott Trotter & His Orchestr...",3,1942,1,1,11940,0,395591396,73,...,96,A,Major,23,19,25,91,0,40,3
439,Agudo Mï¿½ï¿½gi,"Styrx, utku INC, Thezth",3,1930,1,1,323,0,90598517,4,...,130,F#,Minor,65,49,80,22,4,7,5

In [4]:
print(data["released_year"].min())
print(data["released_year"].max())

1930
2023

In [8]:
groupYearly = data.groupby(["released_year"])["track_name"].count().reset_index()
groupYearly.sort_values("track_name",ascending=False)

    released_year  track_name
48           2022         402
49           2023         175
47           2021         119
46           2020          37
45           2019          36
43           2017          23
42           2016          18
39           2013          13
40           2014          13
41           2015          11
44           2018          10
37           2011          10
38           2012          10
36           2010           7
30           2002           6
28           1999           5
32           2004           4
29           2000           4
17           1984           4
8            1963           3
6            1958           3
24           1995           2
31           2003           2
35           2008           2
10           1970           2
5            1957           2
19           1986           2
18           1985           2
15           1982           2
7            1959           2
13           1975           2
21           1991           2
34           2007           1
0            1930           1
33           2005           1
27           1998           1
26           1997           1
1            1942           1
23           1994           1
22           1992           1
20           1987           1
16           1983           1
14           1979           1
12           1973           1
11           1971           1
9            1968           1
4            1952           1
3            1950           1
2            1946           1
25           1996           1

In [9]:
data2022 = data[data["released_year"]==2022]
data2023 = data[data["released_year"]==2023]
data2021 = data[data["released_year"]==2021]

In [16]:
group2022_artists = data2022.groupby(["artist(s)_name"])["track_name"].count().reset_index()
group2022_artists.sort_values("track_name",ascending=False)

                                        artist(s)_name  track_name
217                                                SZA          17
240                                       Taylor Swift          16
16                                           Bad Bunny          15
95                                        Harry Styles          13
243                                         The Weeknd          13
..                                                 ...         ...
105                          John Legend, Metro Boomin           1
107  Jordan Fisher, Josh Levi, Finneas O'Connell, 4...           1
108                                          Jung Kook           1
109                         Justin Bieber, Don Toliver           1
272                                               teto           1

[273 rows x 2 columns]

In [17]:
group2023_artists = data2023.groupby(["artist(s)_name"])["track_name"].count().reset_index()
group2023_artists.sort_values("track_name",ascending=False)

                                    artist(s)_name  track_name
81                                   Morgan Wallen           8
131                                   Taylor Swift           6
51                                           Jimin           3
87                                        NewJeans           3
57                                         Karol G           3
..                                             ...         ...
43                                     IU, Agust D           1
42                                    Halsey, Suga           1
41                                           Gunna           1
40          Grupo Marca Registrada, Grupo Frontera           1
146  sped up nightcore, ARIZONATEARS, Lil Uzi Vert           1

[147 rows x 2 columns]

In [18]:
group2021_artists = data2021.groupby(["artist(s)_name"])["track_name"].count().reset_index()
group2021_artists.sort_values("track_name",ascending=False)

                                      artist(s)_name  track_name
69                                    Olivia Rodrigo           6
20                                          Doja Cat           4
78                                   Sebastian Yatra           2
10                                     Billie Eilish           2
87                                        The Weeknd           2
..                                               ...         ...
34   Imagine Dragons, League of Legends, JID, Arcane           1
33        Imagine Dragons, League of Legends, Arcane           1
32                                   Imagine Dragons           1
31                                               IVE           1
102                                        Yng Lvcas           1

[103 rows x 2 columns]

In [19]:
group2022_monthlyTracks = data2022.groupby(["released_month"])["track_name"].count().reset_index()
group2022_monthlyTracks

    released_month  track_name
0                1          37
1                2          28
2                3          27
3                4          30
4                5          75
5                6          29
6                7          26
7                8          19
8                9          20
9               10          37
10              11          26
11              12          48

In [20]:
group2023_monthlyTracks = data2023.groupby(["released_month"])["track_name"].count().reset_index()
group2023_monthlyTracks

   released_month  track_name
0               1          19
1               2          23
2               3          37
3               4          21
4               5          29
5               6          32
6               7          14

In [21]:
group2021_monthlyTracks = data2021.groupby(["released_month"])["track_name"].count().reset_index()
group2021_monthlyTracks

    released_month  track_name
0                1           3
1                3           5
2                4           8
3                5           8
4                6          11
5                7           8
6                8          12
7                9          18
8               10          12
9               11          21
10              12          13